global:
  scrape_interval: 5s

remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    write_relabel_configs:
      - source_labels: []
        target_label: site
        replacement: prod

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - node-exporter:9100

  - job_name: 'node_exporter_custom'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    static_configs:
      - targets:
        - 192.168.66.38:9090
    metrics_path: '/metrics/node-exporter'

  - job_name: 'nginx_exporter_custom'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    static_configs:
      - targets:
        - 192.168.66.38:9090
    metrics_path: '/metrics/nginx-exporter'

  - job_name: 'php_fpm_exporter_custom'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    static_configs:
      - targets:
        - 192.168.66.38:9090
    metrics_path: '/metrics/php-fpm-exporter'

  - job_name: 'blackbox_custom'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    metrics_path: '/probe/blackbox-exporter'
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://192.168.66.38
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.66.38:9090

  - job_name: 'blackbox_exporter_custom'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    metrics_path: '/metrics/blackbox-exporter'
    static_configs:
      - targets: ['192.168.66.38:9090']

  - job_name: mysql_exporter_custom
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: <PASS>
    static_configs:
      - targets:
        - 192.168.66.38:9090
    metrics_path: '/metrics/mysql-exporter'